export interface AuctionDetail {
  id: string;
  title: string;
  address: string;
  city: string;
  province: string;
  type: "live" | "online" | "sealed";
  status: "live" | "upcoming" | "ended";
  reservePrice: number;
  reserveFormatted: string;
  currentBid: number;
  currentBidFormatted: string;
  bidCount: number;
  bedrooms: number;
  bathrooms: number;
  floorSize: number;
  erfSize: number;
  startTime: string;
  endTime: string;
  features: string[];
  description: string;
  auctioneer: string;
  auctioneerPhone: string;
  auctioneerEmail: string;
  terms: string[];
  images: string[];
}

export const AUCTION_PROPERTIES: AuctionDetail[] = [
  { id: "A001", title: "Executor Sale - Sandton Estate", address: "15 Rivonia Rd, Sandton", city: "Johannesburg", province: "Gauteng", type: "live", status: "live", reservePrice: 4500000, reserveFormatted: "R 4,500,000", currentBid: 5200000, currentBidFormatted: "R 5,200,000", bidCount: 23, bedrooms: 5, bathrooms: 3, floorSize: 380, erfSize: 900, startTime: "2026-04-01T10:00", endTime: "2026-04-01T14:00", features: ["pool", "garden", "security"], description: "Magnificent estate in prime Sandton location being sold by executor. This sprawling property features 5 bedrooms, 3 bathrooms, a grand entrance hall, formal lounge and dining room, family room, study, and staff quarters. The grounds include a heated swimming pool, landscaped gardens, and a tennis court. A rare opportunity to acquire a trophy property below market value.", auctioneer: "BidX Auctioneers", auctioneerPhone: "+27 11 555 9900", auctioneerEmail: "info@bidx.co.za", terms: ["10% deposit on fall of hammer", "Balance within 30 days", "Sold voetstoots", "Registration required"], images: [] },
  { id: "A002", title: "Bank Repossession - Sea Point Flat", address: "3 Beach Rd, Sea Point", city: "Cape Town", province: "Western Cape", type: "online", status: "live", reservePrice: 1800000, reserveFormatted: "R 1,800,000", currentBid: 2100000, currentBidFormatted: "R 2,100,000", bidCount: 15, bedrooms: 2, bathrooms: 1, floorSize: 75, erfSize: 0, startTime: "2026-03-31T08:00", endTime: "2026-04-02T17:00", features: ["security", "balcony"], description: "Bank-repossessed 2-bedroom apartment in sought-after Sea Point. The unit features an open-plan living area with sea views, modern kitchen, and a private balcony. The building offers 24-hour security, a communal pool, and is walking distance from the Sea Point promenade and restaurants. Sold on a bank instruction — excellent investment opportunity.", auctioneer: "SA Auction Group", auctioneerPhone: "+27 21 444 8800", auctioneerEmail: "cape@saauction.co.za", terms: ["5% deposit on fall of hammer", "Balance within 45 days", "Subject to confirmation", "Valid ID required"], images: [] },
  { id: "A003", title: "Commercial Unit - Menlyn", address: "Menlyn Maine, Pretoria", city: "Pretoria", province: "Gauteng", type: "sealed", status: "upcoming", reservePrice: 6200000, reserveFormatted: "R 6,200,000", currentBid: 0, currentBidFormatted: "-", bidCount: 0, bedrooms: 0, bathrooms: 2, floorSize: 250, erfSize: 0, startTime: "2026-04-10T09:00", endTime: "2026-04-10T16:00", features: ["aircon", "fibre", "security"], description: "Prime commercial office space in the prestigious Menlyn Maine precinct. This modern unit spans 250m² across an open-plan layout with two private offices, boardroom, kitchenette, and two bathrooms. The building features fibre connectivity, central air conditioning, backup power, and secure basement parking. Ideal for corporate tenants or owner-occupiers.", auctioneer: "BidX Auctioneers", auctioneerPhone: "+27 11 555 9900", auctioneerEmail: "info@bidx.co.za", terms: ["Sealed bid submission by 16:00", "10% deposit required", "Balance within 60 days", "Subject to reserve"], images: [] },
  { id: "A004", title: "Luxury Villa - Umhlanga", address: "12 Lighthouse Rd, Umhlanga", city: "Durban", province: "KwaZulu-Natal", type: "live", status: "upcoming", reservePrice: 9800000, reserveFormatted: "R 9,800,000", currentBid: 0, currentBidFormatted: "-", bidCount: 0, bedrooms: 4, bathrooms: 4, floorSize: 350, erfSize: 800, startTime: "2026-04-15T10:00", endTime: "2026-04-15T13:00", features: ["pool", "garden", "security", "balcony"], description: "Luxurious contemporary villa in exclusive Umhlanga with ocean views. This architectural gem features 4 en-suite bedrooms, a chef's kitchen, home cinema, wine cellar, infinity pool, and expansive entertainment deck. Smart home automation throughout. Set in a secure gated community minutes from Gateway Shopping Centre and Umhlanga Village.", auctioneer: "KZN Auctions", auctioneerPhone: "+27 31 333 7700", auctioneerEmail: "info@kznauctions.co.za", terms: ["10% deposit on fall of hammer", "Balance within 30 days", "Sold voetstoots", "Inspection by appointment"], images: [] },
  { id: "A005", title: "Farm Property - Stellenbosch", address: "Wine Route Rd, Stellenbosch", city: "Stellenbosch", province: "Western Cape", type: "online", status: "upcoming", reservePrice: 7500000, reserveFormatted: "R 7,500,000", currentBid: 0, currentBidFormatted: "-", bidCount: 0, bedrooms: 3, bathrooms: 2, floorSize: 280, erfSize: 50000, startTime: "2026-04-20T08:00", endTime: "2026-04-22T17:00", features: ["garden", "borehole", "staffQuarters"], description: "Working wine farm on the renowned Stellenbosch Wine Route. The property includes a Cape Dutch homestead with 3 bedrooms, 5 hectares of established vineyards (Cabernet Sauvignon and Merlot), a cellar building, staff accommodation, and farm equipment. Current wine production of 15,000 cases annually. An exceptional opportunity for wine enthusiasts and investors alike.", auctioneer: "SA Auction Group", auctioneerPhone: "+27 21 444 8800", auctioneerEmail: "cape@saauction.co.za", terms: ["10% deposit required", "Balance within 90 days", "Wine stock negotiable", "Due diligence period of 14 days"], images: [] },
  { id: "A006", title: "Townhouse - Midrand Complex", address: "44 Waterfall Dr, Midrand", city: "Midrand", province: "Gauteng", type: "online", status: "ended", reservePrice: 1600000, reserveFormatted: "R 1,600,000", currentBid: 1950000, currentBidFormatted: "R 1,950,000", bidCount: 31, bedrooms: 3, bathrooms: 2, floorSize: 140, erfSize: 200, startTime: "2026-03-20T08:00", endTime: "2026-03-22T17:00", features: ["garden", "security"], description: "Modern 3-bedroom townhouse in the popular Waterfall Country Estate. Features include an open-plan living area, fitted kitchen, private garden, and double garage. The estate offers extensive amenities including a clubhouse, swimming pool, tennis courts, and walking trails. Easy access to the N1 and Mall of Africa.", auctioneer: "BidX Auctioneers", auctioneerPhone: "+27 11 555 9900", auctioneerEmail: "info@bidx.co.za", terms: ["Auction concluded", "Final bid: R 1,950,000", "31 total bids received"], images: [] },
  { id: "A007", title: "Industrial Warehouse - Montague", address: "Industrial Park, Montague Gardens", city: "Cape Town", province: "Western Cape", type: "sealed", status: "ended", reservePrice: 3200000, reserveFormatted: "R 3,200,000", currentBid: 3600000, currentBidFormatted: "R 3,600,000", bidCount: 8, bedrooms: 0, bathrooms: 1, floorSize: 600, erfSize: 1500, startTime: "2026-03-15T09:00", endTime: "2026-03-15T15:00", features: ["security"], description: "Large industrial warehouse in Montague Gardens with excellent highway access. The property includes 600m² of warehouse space with 6m eaves height, a small office section, loading bay, and secure yard. Zoned General Industrial with high power supply. Ideal for distribution, manufacturing, or storage operations.", auctioneer: "SA Auction Group", auctioneerPhone: "+27 21 444 8800", auctioneerEmail: "cape@saauction.co.za", terms: ["Auction concluded", "Final bid: R 3,600,000", "8 sealed bids received"], images: [] },
  { id: "A008", title: "Penthouse - Rosebank", address: "The Firs, Rosebank", city: "Johannesburg", province: "Gauteng", type: "live", status: "upcoming", reservePrice: 5500000, reserveFormatted: "R 5,500,000", currentBid: 0, currentBidFormatted: "-", bidCount: 0, bedrooms: 3, bathrooms: 2, floorSize: 200, erfSize: 0, startTime: "2026-04-25T10:00", endTime: "2026-04-25T13:00", features: ["gym", "security", "balcony", "aircon"], description: "Spectacular penthouse in the heart of Rosebank with 360-degree views of the Johannesburg skyline. This top-floor unit features 3 bedrooms, 2 luxurious bathrooms, a gourmet kitchen with Miele appliances, and an expansive wrap-around balcony. Building amenities include a residents' gym, concierge, and secure basement parking. Steps from the Rosebank Mall and Gautrain.", auctioneer: "BidX Auctioneers", auctioneerPhone: "+27 11 555 9900", auctioneerEmail: "info@bidx.co.za", terms: ["10% deposit on fall of hammer", "Balance within 30 days", "Subject to reserve", "Registration opens 09:00"], images: [] },
];

export function getAuctionById(id: string): AuctionDetail | undefined {
  return AUCTION_PROPERTIES.find((a) => a.id === id);
}
