export interface BusinessDetail {
  id: string;
  name: string;
  category: string;
  location: string;
  city: string;
  province: string;
  askingPrice: number;
  askingPriceFormatted: string;
  monthlyRevenue: string;
  monthlyProfit: string;
  annualRevenue: string;
  annualProfit: string;
  employees: number;
  yearsEstablished: number;
  description: string;
  highlights: string[];
  status: string;
  franchise: boolean;
  operatingHours: string;
  reasonForSale: string;
  assets: string[];
  agentName: string;
  agentPhone: string;
  agentEmail: string;
}

export const BUSINESS_LISTINGS: BusinessDetail[] = [
  { id: "B001", name: "Artisan Coffee Roastery & Cafe", category: "hospitality", location: "44th Ave, Parkhurst, Johannesburg", city: "Johannesburg", province: "Gauteng", askingPrice: 2200000, askingPriceFormatted: "R 2,200,000", monthlyRevenue: "R 380,000", monthlyProfit: "R 85,000", annualRevenue: "R 4,560,000", annualProfit: "R 1,020,000", employees: 12, yearsEstablished: 6, description: "Well-established specialty coffee brand with roastery, two retail locations, and wholesale accounts. The business has built a loyal following in the Parkhurst area and supplies roasted beans to 15+ restaurants and offices. The roastery operates from a 120m\u00B2 facility with a Probat roaster and full cupping lab. Both retail locations are profitable with strong foot traffic. All recipes, supplier relationships, and operational systems are documented and transferable.", highlights: ["loyal customer base", "own roasting facility", "wholesale contracts"], status: "available", franchise: false, operatingHours: "Mon-Fri 6:30-17:00, Sat-Sun 7:00-15:00", reasonForSale: "Owner relocating internationally", assets: ["Probat 15kg roaster", "2 espresso machines (La Marzocca)", "Cupping lab equipment", "Delivery van", "POS systems", "Furniture & fixtures"], agentName: "Lisa Fourie", agentPhone: "+27 82 777 8888", agentEmail: "lisa@propertyfinder.com" },
  { id: "B002", name: "Premium Car Wash Franchise", category: "franchise", location: "N1 Highway, Midrand", city: "Midrand", province: "Gauteng", askingPrice: 950000, askingPriceFormatted: "R 950,000", monthlyRevenue: "R 220,000", monthlyProfit: "R 65,000", annualRevenue: "R 2,640,000", annualProfit: "R 780,000", employees: 8, yearsEstablished: 3, description: "Turnkey franchise operation with established brand, high traffic location, and proven systems. Located on the N1 highway with excellent visibility and easy access. The franchise package includes full training, marketing support, and operational manuals. Current owner operates semi-absentee with a trained manager on site. Consistent monthly revenues with seasonal peaks during dry months.", highlights: ["franchise support", "high-traffic location", "repeat customers"], status: "newListing", franchise: true, operatingHours: "Mon-Sat 7:00-18:00, Sun 8:00-16:00", reasonForSale: "Franchise portfolio restructuring", assets: ["Wash bay equipment (4 bays)", "Water recycling system", "Waiting lounge furniture", "POS system", "Franchise licence (5 years remaining)"], agentName: "Pieter de Wet", agentPhone: "+27 83 111 2222", agentEmail: "pieter@propertyfinder.com" },
  { id: "B003", name: "IT Solutions & Managed Services", category: "services", location: "Sandton CBD", city: "Johannesburg", province: "Gauteng", askingPrice: 4800000, askingPriceFormatted: "R 4,800,000", monthlyRevenue: "R 650,000", monthlyProfit: "R 180,000", annualRevenue: "R 7,800,000", annualProfit: "R 2,160,000", employees: 22, yearsEstablished: 10, description: "B2B managed IT services with 60+ recurring corporate clients and long-term contracts. The company provides network management, cloud services, cybersecurity, and helpdesk support. Revenue is 85% recurring from multi-year SLA contracts. The team includes certified engineers (Microsoft, Cisco, AWS) and a dedicated sales team. Strong relationships with major technology vendors ensure competitive margins on hardware and licensing.", highlights: ["recurring revenue", "long-term contracts", "skilled team"], status: "available", franchise: false, operatingHours: "24/7 support, office hours Mon-Fri 8:00-17:00", reasonForSale: "Founder retirement", assets: ["Client contracts (avg 3 years)", "Monitoring infrastructure", "Office equipment", "Company vehicles (3)", "Software licences", "Brand & IP"], agentName: "Lisa Fourie", agentPhone: "+27 82 777 8888", agentEmail: "lisa@propertyfinder.com" },
  { id: "B004", name: "Boutique Guest House", category: "hospitality", location: "Franschhoek Main Rd", city: "Franschhoek", province: "Western Cape", askingPrice: 8500000, askingPriceFormatted: "R 8,500,000", monthlyRevenue: "R 520,000", monthlyProfit: "R 150,000", annualRevenue: "R 6,240,000", annualProfit: "R 1,800,000", employees: 15, yearsEstablished: 12, description: "Award-winning 8-room guest house in the heart of wine country with restaurant and pool. The property has been lovingly maintained and upgraded, earning a 4.8-star TripAdvisor rating and inclusion in several 'best of' guides. Each room is individually decorated with luxury finishes. The on-site restaurant seats 40 and is popular with locals and guests alike. The property includes the building, land, and all furnishings. Occupancy averages 75% year-round with peak season December-March.", highlights: ["prime wine region", "TripAdvisor rated", "includes property"], status: "available", franchise: false, operatingHours: "24/7 (guest accommodation), Restaurant: Tue-Sun", reasonForSale: "Owner retiring after 12 years", assets: ["Property (8 rooms + restaurant)", "All furniture & equipment", "Commercial kitchen", "Wine cellar (stock negotiable)", "Booking system & website", "Vehicle (guest shuttle)"], agentName: "Pieter de Wet", agentPhone: "+27 83 111 2222", agentEmail: "pieter@propertyfinder.com" },
  { id: "B005", name: "E-Commerce Fashion Brand", category: "online", location: "Remote / Cape Town HQ", city: "Cape Town", province: "Western Cape", askingPrice: 1500000, askingPriceFormatted: "R 1,500,000", monthlyRevenue: "R 280,000", monthlyProfit: "R 95,000", annualRevenue: "R 3,360,000", annualProfit: "R 1,140,000", employees: 4, yearsEstablished: 4, description: "Online fashion brand with 50K+ social followers, Shopify store, and strong brand identity. The business designs and sells a curated collection of contemporary women's fashion sourced from local and international manufacturers. The Shopify store generates consistent sales with an average order value of R850. Social media presence includes 35K Instagram and 15K TikTok followers with high engagement rates. The business operates with minimal overheads from a small Cape Town office and warehouse.", highlights: ["50K social following", "low overheads", "scalable"], status: "priceReduced", franchise: false, operatingHours: "Online 24/7, Office Mon-Fri 9:00-17:00", reasonForSale: "Founders pursuing new venture", assets: ["Shopify store & domain", "Social media accounts", "Brand assets & designs", "Current inventory (R200K)", "Supplier relationships", "Email list (25K subscribers)"], agentName: "Lisa Fourie", agentPhone: "+27 82 777 8888", agentEmail: "lisa@propertyfinder.com" },
  { id: "B006", name: "Industrial Packaging Manufacturer", category: "manufacturing", location: "Prospecton Industrial, Durban", city: "Durban", province: "KwaZulu-Natal", askingPrice: 6200000, askingPriceFormatted: "R 6,200,000", monthlyRevenue: "R 890,000", monthlyProfit: "R 220,000", annualRevenue: "R 10,680,000", annualProfit: "R 2,640,000", employees: 35, yearsEstablished: 18, description: "Established packaging business supplying FMCG sector with modern machinery and warehouse. The company manufactures corrugated boxes, shrink wrap, and custom packaging solutions for major food and beverage brands. The facility spans 2,000m\u00B2 with modern production lines, a design studio, and warehousing. Long-standing relationships with blue-chip clients ensure stable revenue. The business holds ISO 9001 certification and exports to three neighbouring countries.", highlights: ["FMCG clients", "modern machinery", "export ready"], status: "underNegotiation", franchise: false, operatingHours: "Mon-Fri 6:00-18:00 (two shifts)", reasonForSale: "Strategic divestment by holding company", assets: ["Production machinery", "2,000m\u00B2 facility (leased)", "Delivery fleet (4 trucks)", "Design software & IP", "ISO 9001 certification", "Raw material stock"], agentName: "Pieter de Wet", agentPhone: "+27 83 111 2222", agentEmail: "pieter@propertyfinder.com" },
  { id: "B007", name: "Retail Clothing Store Chain", category: "retail", location: "3 Locations, Gauteng", city: "Johannesburg", province: "Gauteng", askingPrice: 3400000, askingPriceFormatted: "R 3,400,000", monthlyRevenue: "R 480,000", monthlyProfit: "R 110,000", annualRevenue: "R 5,760,000", annualProfit: "R 1,320,000", employees: 20, yearsEstablished: 8, description: "Three trendy retail locations in major malls with established brand and loyal customer base. The stores carry a mix of own-brand and curated fashion for men and women aged 25-40. Each location averages 150m\u00B2 in high-traffic mall positions. The business has established vendor relationships in China and Turkey for competitive margins. All three locations are profitable with trained managers in place.", highlights: ["3 retail locations", "mall presence", "own brand"], status: "available", franchise: false, operatingHours: "Mall trading hours (typically 9:00-21:00)", reasonForSale: "Owner emigrating", assets: ["Inventory (R600K at cost)", "Shop fittings x3", "POS systems x3", "Lease agreements (2+ years each)", "Brand & trademarks", "Vendor relationships"], agentName: "Lisa Fourie", agentPhone: "+27 82 777 8888", agentEmail: "lisa@propertyfinder.com" },
  { id: "B008", name: "Quick-Service Restaurant Franchise", category: "franchise", location: "Menlyn Park, Pretoria", city: "Pretoria", province: "Gauteng", askingPrice: 1800000, askingPriceFormatted: "R 1,800,000", monthlyRevenue: "R 350,000", monthlyProfit: "R 75,000", annualRevenue: "R 4,200,000", annualProfit: "R 900,000", employees: 14, yearsEstablished: 5, description: "Popular fast-food franchise in high-traffic mall with drive-through option. This well-known brand benefits from national advertising, proven recipes, and comprehensive operational support. Located in Menlyn Park with both mall-facing and drive-through access. The unit consistently ranks in the top 20% of franchisees nationally. All equipment recently serviced and in excellent condition.", highlights: ["mall location", "drive-through", "strong brand"], status: "newListing", franchise: true, operatingHours: "Daily 8:00-22:00, Drive-through to 23:00", reasonForSale: "Multi-unit owner consolidating", assets: ["Kitchen equipment", "Drive-through infrastructure", "POS & ordering systems", "Franchise licence (7 years remaining)", "Staff uniforms & training materials", "Signage"], agentName: "Pieter de Wet", agentPhone: "+27 83 111 2222", agentEmail: "pieter@propertyfinder.com" },
];

export function getBusinessById(id: string): BusinessDetail | undefined {
  return BUSINESS_LISTINGS.find((b) => b.id === id);
}
